### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by csguoh** [AVC2-UESTC/CRAFT-SR#1]
Hi authors.
Thanks for your incredible work! I want to know when the code will be available?

**Comment by cenchaojun** [comment]
also wait

**Comment by Lumos-Leo** [comment]
Hi @csguoh @cenchaojun ,
Thanks for your interest. We're wrapping up some code-related tasks and will open-source it as soon as they're complete. Your patience is much appreciated.

**Comment by wangxinchao-bit** [comment]
also wait for the source code

**Comment by Lumos-Leo** [comment]
Thank you for your interest in our work. We've released our code.
