### ISSUE TITLE
UnboundLocalError: local variable 'img_gt' referenced before assignment

### ISSUE THREAD

**Issue by danganyuan** [AVC2-UESTC/CRAFT-SR#10]
请问测试时出现这个问题 是什么情况呢

**Comment by Lumos-Leo** [comment]
hi 如果给出全部报错信息可能能更好定位问题 目前从error来看 应该是在对img_gt变量赋值之前 就使用了这个变量

**Comment by danganyuan** [comment]
> hi 如果给出全部报错信息可能能更好定位问题 目前从error来看 应该是在对img_gt变量赋值之前 就使用了这个变量

请问我只有一个gpu并在Windows系统下 应该如何训练这个模型呢

**Comment by Lumos-Leo** [comment]
hi，你好， 
1. 抱歉，我们没有在Windows下训练过，但可以先在Windows下载conda然后按着readme配置一下环境试试；
2. 如果只有一个gpu的话，建议调整配置文件的batchsize为32，然后在运行脚本时将gpu设置为1。如果显存不够，只能减少batchsize来训练，但可能性能会有所降低。
