### ISSUE TITLE
KeyError: "No object named 'CRAFT' found in 'arch' registry!

### ISSUE THREAD

**Issue by danganyuan** [AVC2-UESTC/CRAFT-SR#11]
请问我再训练时一直遇到这个问题  您有遇到过吗  应该如何解决呢

**Comment by Lumos-Leo** [comment]
你好 看起来是模型没有正确注册 可以打断点到这个文件 https://github.com/AVC2-UESTC/CRAFT-SR/blob/f4f706816fdd186529fd8b7ffebfb3446be43e8d/basicsr/archs/__init__.py#L15 看看路径是否存在问题
