### ISSUE TITLE
About patches size while training.

### ISSUE THREAD

**Issue by IceyWuu** [AVC2-UESTC/CRAFT-SR#13]
I saw in your paper that you randomly crop the images into 64 × 64 patches during training. Where can I set this for different sizes? Is it the 'gt_size' in the .yml files?
I'm new here and still struggling with the code.

**Comment by Lumos-Leo** [comment]
Yes, you can directly modify the gt_size in the .yml file to set the size for different patch sizes. Just change the value to whatever size you need, and it should work!
