### ISSUE TITLE
参考论文的指标问题

### ISSUE THREAD

**Issue by taoWuuu** [AVC2-UESTC/CRAFT-SR#14]
请问您论文中EDSR-baseline的指标是什么地方得到的，因为我在EDSR原文中发现他们并没有提供baseline在其他基准数据集上的测试结果，是自己从头训练的吗还是说在其他论文里面看到的，例如ELAN那篇论文？

**Comment by Lumos-Leo** [comment]
hi，你好，EDSR的预训练权重请参考：https://github.com/sanghyun-son/EDSR-PyTorch/blob/8dba5581a7502b92de9641eb431130d6c8ca5d7f/src/model/edsr.py#L5

**Comment by taoWuuu** [comment]
好的谢谢
