### ISSUE TITLE
Visualization of HFERB and SRWAB.

### ISSUE THREAD

**Issue by Fly175** [AVC2-UESTC/CRAFT-SR#4]
I've been looking for structural visualization code lately, and you can provide you with the code visualization in your paper or what you can do to use it. Thank you

**Comment by Lumos-Leo** [comment]
Please refer to the code at [this link](https://github.com/Lumos-Leo/CV_Visualization/blob/fec7548810c776902c7636e8a6b5d306e5d74087/visualization/features_ops.py#L14) for visualizing the block.
