### ISSUE TITLE
Swin IR  and  LAM

### ISSUE THREAD

**Issue by SJHunag** [AVC2-UESTC/CRAFT-SR#8]
I encountered this situation while doing LAM, please seek help！
![image](https://github.com/AVC2-UESTC/CRAFT-SR/assets/144510623/4a1ac483-abe1-4032-bcbe-fd1746d69d52)

**Comment by Lumos-Leo** [comment]
Sorry, we do not encounter this issue, but from the figures, it seems that you have already obtained the visual results?
