### ISSUE TITLE
关于图像高频低频的咨询

### ISSUE THREAD

**Issue by QingjunRu** [AVC2-UESTC/CRAFT-SR#9]
作者您好，最近阅读到您的文章“Feature Modulation Transformer: Cross-Reﬁnement of Global Representation via High-Frequency Prior for Image Super-Resolution”。
文章中提到将图像频谱拉平后按照幅度排序，在选择阈值来剔除高频信息，因此有个问题想向您咨询：
图像频谱中，不是说离中心点越远，代表频率越高吗，幅度只是代表某个频率的分量占的比重，为什么安幅度排序可以剔除高频信息呢？

**Comment by Lumos-Leo** [comment]
hi，感谢关注！是的，仅凭幅度并不能准确剔除高频分量，如图1所示，频谱图并非理想的矩形结构。我们的做法是基于一种简化的假设，即在许多自然图像中，低频分量通常具有较大的能量或幅度，而高频分量往往幅度较小。因此，通过按幅度排序并丢弃幅度较小的频率分量，可以有效去除一部分高频信息。

**Comment by QingjunRu** [comment]
我明白了，非常感谢您的解惑！
